// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERIALMAIL_SERIALMAIL_H_
#define FLATBUFFERS_GENERATED_SERIALMAIL_SERIALMAIL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 24,
             "Non-compatible flatbuffers version included");

namespace SerialMail {

struct Value;

struct SerialMail;
struct SerialMailBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Value FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_0_;
  uint8_t data_1_;
  uint8_t data_2_;

 public:
  Value()
      : data_0_(0),
        data_1_(0),
        data_2_(0) {
  }
  Value(uint8_t _data_0, uint8_t _data_1, uint8_t _data_2)
      : data_0_(::flatbuffers::EndianScalar(_data_0)),
        data_1_(::flatbuffers::EndianScalar(_data_1)),
        data_2_(::flatbuffers::EndianScalar(_data_2)) {
  }
  uint8_t data_0() const {
    return ::flatbuffers::EndianScalar(data_0_);
  }
  uint8_t data_1() const {
    return ::flatbuffers::EndianScalar(data_1_);
  }
  uint8_t data_2() const {
    return ::flatbuffers::EndianScalar(data_2_);
  }
};
FLATBUFFERS_STRUCT_END(Value, 3);

struct SerialMail FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SerialMailBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INPUTS_CH0 = 4,
    VT_INPUTS_CH1 = 6,
    VT_CLASSIFICATION_CH0 = 8,
    VT_CLASSIFICATION_CH1 = 10
  };
  const ::flatbuffers::Vector<const Value *> *inputs_ch0() const {
    return GetPointer<const ::flatbuffers::Vector<const Value *> *>(VT_INPUTS_CH0);
  }
  const ::flatbuffers::Vector<const Value *> *inputs_ch1() const {
    return GetPointer<const ::flatbuffers::Vector<const Value *> *>(VT_INPUTS_CH1);
  }
  const ::flatbuffers::Vector<float> *classification_ch0() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_CLASSIFICATION_CH0);
  }
  const ::flatbuffers::Vector<float> *classification_ch1() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_CLASSIFICATION_CH1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INPUTS_CH0) &&
           verifier.VerifyVector(inputs_ch0()) &&
           VerifyOffset(verifier, VT_INPUTS_CH1) &&
           verifier.VerifyVector(inputs_ch1()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION_CH0) &&
           verifier.VerifyVector(classification_ch0()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION_CH1) &&
           verifier.VerifyVector(classification_ch1()) &&
           verifier.EndTable();
  }
};

struct SerialMailBuilder {
  typedef SerialMail Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_inputs_ch0(::flatbuffers::Offset<::flatbuffers::Vector<const Value *>> inputs_ch0) {
    fbb_.AddOffset(SerialMail::VT_INPUTS_CH0, inputs_ch0);
  }
  void add_inputs_ch1(::flatbuffers::Offset<::flatbuffers::Vector<const Value *>> inputs_ch1) {
    fbb_.AddOffset(SerialMail::VT_INPUTS_CH1, inputs_ch1);
  }
  void add_classification_ch0(::flatbuffers::Offset<::flatbuffers::Vector<float>> classification_ch0) {
    fbb_.AddOffset(SerialMail::VT_CLASSIFICATION_CH0, classification_ch0);
  }
  void add_classification_ch1(::flatbuffers::Offset<::flatbuffers::Vector<float>> classification_ch1) {
    fbb_.AddOffset(SerialMail::VT_CLASSIFICATION_CH1, classification_ch1);
  }
  explicit SerialMailBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SerialMail> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SerialMail>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SerialMail> CreateSerialMail(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Value *>> inputs_ch0 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Value *>> inputs_ch1 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> classification_ch0 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> classification_ch1 = 0) {
  SerialMailBuilder builder_(_fbb);
  builder_.add_classification_ch1(classification_ch1);
  builder_.add_classification_ch0(classification_ch0);
  builder_.add_inputs_ch1(inputs_ch1);
  builder_.add_inputs_ch0(inputs_ch0);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SerialMail> CreateSerialMailDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<Value> *inputs_ch0 = nullptr,
    const std::vector<Value> *inputs_ch1 = nullptr,
    const std::vector<float> *classification_ch0 = nullptr,
    const std::vector<float> *classification_ch1 = nullptr) {
  auto inputs_ch0__ = inputs_ch0 ? _fbb.CreateVectorOfStructs<Value>(*inputs_ch0) : 0;
  auto inputs_ch1__ = inputs_ch1 ? _fbb.CreateVectorOfStructs<Value>(*inputs_ch1) : 0;
  auto classification_ch0__ = classification_ch0 ? _fbb.CreateVector<float>(*classification_ch0) : 0;
  auto classification_ch1__ = classification_ch1 ? _fbb.CreateVector<float>(*classification_ch1) : 0;
  return CreateSerialMail(
      _fbb,
      inputs_ch0__,
      inputs_ch1__,
      classification_ch0__,
      classification_ch1__);
}

inline const SerialMail *GetSerialMail(const void *buf) {
  return ::flatbuffers::GetRoot<SerialMail>(buf);
}

inline const SerialMail *GetSizePrefixedSerialMail(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SerialMail>(buf);
}

inline bool VerifySerialMailBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SerialMail>(nullptr);
}

inline bool VerifySizePrefixedSerialMailBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SerialMail>(nullptr);
}

inline void FinishSerialMailBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SerialMail> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSerialMailBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SerialMail> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SerialMail

#endif  // FLATBUFFERS_GENERATED_SERIALMAIL_SERIALMAIL_H_
